import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import numpy as np
import os

from tiny_notebook import Notebook, Chart

class PritnfCallback(keras.callbacks.Callback):
    def __init__(self, print):
        self._print = print

    def on_epoch_begin(self, epoch, logs=None):
        self._print('on_epoch_begin', epoch, logs)

    def on_epoch_end(self, epoch, logs=None):
        self._print('on_epoch_end', epoch, logs)

    def on_batch_begin(self, batch, logs=None):
        self._print('on_batch_begin', batch, logs)

    def on_batch_end(self, batch, logs=None):
        self._print('on_batch_end', batch, logs)

    def on_train_begin(self, logs=None):
        self._print('on_train_begin', logs)

    def on_train_end(self, logs=None):
        self._print('on_train_end', logs)

with Notebook() as print:
    print('CIFAR CNN', fmt='header', level=1)
    num_classes = 10
    num_predictions = 20
    save_dir = os.path.join(os.getcwd(), 'saved_models')
    model_name = 'keras_cifar10_trained_model.h5'

    # The data, shuffled and split between train and test sets:
    print('Data Statistics', fmt='header', level=3)
    (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    print('x_train shape:', x_train.shape)
    print('y_train shape:', y_train.shape)
    print('x_test shape:', x_test.shape)
    print('y_test shape:', y_test.shape)
    print('y_train example:', list(map(int, y_train[:10])))

    print.header('x_train', level=4)
    indices = np.random.choice(len(x_train), size=12)
    print.img(x_train[indices], caption=y_train[indices], width=117)

    # Convert class vectors to binary class matrices.
    y_train = keras.utils.to_categorical(y_train, num_classes)
    y_test = keras.utils.to_categorical(y_test, num_classes)
    print.header('categorical')
    print(y_train[:20])

    model = Sequential()
    model.add(Conv2D(32, (3, 3), padding='same',
                     input_shape=x_train.shape[1:]))

    model.add(Activation('relu'))
    model.add(Conv2D(64, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(num_classes))
    model.add(Activation('softmax'))

    # Let's train the model using RMSprop
    model.compile(loss='categorical_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 255
    x_test /= 255

    model.fit(x_train, y_train,
      batch_size=30,
      epochs=100,
      validation_data=(x_test, y_test),
      callbacks=[PritnfCallback(print)],
      shuffle=True)


    # if not config.data_augmentation:
    #     print('Not using data augmentation.')
    #     model.fit(x_train, y_train,
    #               batch_size=batch_size,
    #               epochs=epochs,
    #               validation_data=(x_test, y_test),
    #               callbacks=[WandbKerasCallback],
    #               shuffle=True)
    # else:
    #     print('Using real-time data augmentation.')
    #     # This will do preprocessing and realtime data augmentation:
    #     datagen = ImageDataGenerator(
    #         featurewise_center=False,  # set input mean to 0 over the dataset
    #         samplewise_center=False,  # set each sample mean to 0
    #         featurewise_std_normalization=False,  # divide inputs by std of the dataset
    #         samplewise_std_normalization=False,  # divide each input by its std
    #         zca_whitening=False,  # apply ZCA whitening
    #         rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
    #         width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
    #         height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
    #         horizontal_flip=True,  # randomly flip images
    #         vertical_flip=False)  # randomly flip images
    #
    #     # Compute quantities required for feature-wise normalization
    #     # (std, mean, and principal components if ZCA whitening is applied).
    #     datagen.fit(x_train)
    #
    #     # Fit the model on the batches generated by datagen.flow().
    #     model.fit_generator(datagen.flow(x_train, y_train,
    #                                      batch_size=config.batch_size),
    #                         steps_per_epoch=(x_train.shape[0] // config.batch_size) // 20,
    #                         epochs=config.epochs,
    #                         validation_data=(x_test[:200], y_test[:200]),
    #                         workers=4,
    #                         callbacks=[WandbKerasCallback()]
    #     )
    #
    # # Save model and weights
    # if not os.path.isdir(save_dir):
    #     os.makedirs(save_dir)
    #
    # model_path = os.path.join(save_dir, model_name)
    # model.save(model_path)
    # print('Saved trained model at %s ' % model_path)
    #
    # # Score trained model.
    # scores = model.evaluate(x_test, y_test, verbose=1)
    # print('Test loss:', scores[0])
    # print('Test accuracy:', scores[1])
