[rules]
unresolved-import = "ignore"
# This rule has problems with the ParamSpec support:
# https://github.com/astral-sh/ty/issues/157
invalid-type-form = "ignore"

[environment]
root = ["./lib/streamlit"]

[src]
include = ["lib/streamlit", "e2e_playwright", "scripts"]
exclude = ["e2e_playwright/compilation_error_dialog.py"]
