name: Bug report
description: Submit a bug report to help us improve Streamlit.
labels: [bug, needs triage]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I have searched the [existing issues](https://github.com/streamlit/streamlit/issues) for similar issues.
          required: true
        - label: I have searched the [Streamlit documentation](https://docs.streamlit.io/).
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: Type here a clear and concise description of the bug. Aim for 2-3 sentences.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducible Code Example
      render: Python
      description: |
        If applicable, please provide a [self-contained minimal code example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem you ran into.

        If we can copy it, run it, and see it right away, there's a much higher chance we will be able to help you.
      placeholder: |
        import streamlit as st

        st.write("Hello World")
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Please provide the steps we should take to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Explain what you expect to happen when you go through the steps above, assuming there were no bugs.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      placeholder: |
        Error message:

        ```
        streamlit.errors.StreamlitAPIException ...
        ```
      description: |
        Explain the buggy behavior you experience when you go through the steps above.
        If you have error messages or stack traces please provide them here as well.
        If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Is this a regression?
      description: That is, did this use to work the way you expected in the past?
      options:
        - "Yes"
        - "No"
        - "I don't know"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Debug info
      description: |
        Example:
          - **Streamlit version**: 1.13.0
          - **Python version**: 3.9
          - **Virtual environment**: Pipenv
          - **OS**: MacOs 12.6
          - **Browser**: Chrome
      value: |
        - Streamlit version: (get it with `$ streamlit version`)
        - Python version: (get it with `$ python --version`)
        - Virtual environment: (Conda? PipEnv? PyEnv? Pex?)
        - OS:
        - Browser:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        For example, did this bug come from https://discuss.streamlit.io or another site? Link the original source here!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
