name: "Set PYTHON_MIN_VERSION & PYTHON_MAX_VERSION"
description: "Add $PYTHON_MIN_VERSION and $PYTHON_MAX_VERSION to the $GITHUB_ENV object.
  Edit this action to change the min or max Python versions we test against."

runs:
  using: composite
  steps:
    - run: |
        echo "PYTHON_MIN_VERSION=3.7" >> $GITHUB_ENV
        echo "PYTHON_MAX_VERSION=3.10" >> $GITHUB_ENV
      shell: bash --login -eo pipefail {0}
