name: "Pre-Cache"
runs:
  using: composite
  steps:
    # Combine hashes of the Python interpreter, Pipfile, and today's
    # date into a file whose checksum will key the Python virtualenv.
    #
    # This means that our virtualenv cache will expire each day. We do
    # this because we are not using a lockfile to pin dependencies -
    # instead, each time CircleCI rebuilds the virtualenv, it uses the
    # latest compatible version of each dependency (which mirrors what
    # happens when a user installs Streamlit locally). So we expire our
    # virtualenv cache daily to prevent it from getting far out of sync
    # with what a fresh Streamlit installation would look like.
    - name: Create Python environment cache key
      run: |
        md5sum $(which python) > $GITHUB_WORKSPACE/python_cache_key.md5
        md5sum lib/Pipfile >> $GITHUB_WORKSPACE/python_cache_key.md5
        md5sum lib/test-requirements.txt >> $GITHUB_WORKSPACE/python_cache_key.md5
        md5sum lib/test-requirements-with-tensorflow.txt >> $GITHUB_WORKSPACE/python_cache_key.md5
        md5sum lib/setup.py >> $GITHUB_WORKSPACE/python_cache_key.md5
        date +%F >> $GITHUB_WORKSPACE/python_cache_key.md5
      shell: bash -ileo pipefail {0}
