{
 "title": "Nvidia GPU",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "nvidia_gpu_duty_cycle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_duty_cycle" }
   ]
  },
  {
   "title": "nvidia_gpu_memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_memory_used_bytes", "legendFormat": "used" },
    { "expr": "nvidia_gpu_memory_total_bytes", "legendFormat": "total" }
   ]
  },
  {
   "title": "nvidia_gpu_num_devices",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_num_devices" }
   ]
  },
  {
   "title": "nvidia_gpu_power_usage_milliwatts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_power_usage_milliwatts"
    }
   ]
  },
  {
   "title": "nvidia_gpu_temperature_celsius",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "nvidia_gpu_temperature_celsius", "legendFormat": "celcius" },
    {
     "expr": "(nvidia_gpu_temperature_celsius * 9/5) + 32",
     "legendFormat": "fahrenheit"
    }
   ]
  }
 ]
}