{
 "title": "Process",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": "up" }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:up:count{job=\"${job}\"}",
     "legendFormat": "configured"
    },
    {
     "expr": "job:up:sum{job=\"${job}\"}",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - job:process_start_time_seconds:max{job=\"${job}\"}",
     "legendFormat": "max"
    },
    {
     "expr": "time() - job:process_start_time_seconds:min{job=\"${job}\"}",
     "legendFormat": "min"
    },
    {
     "expr": "time() - job:process_start_time_seconds:median{job=\"${job}\"}",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:process_cpu_seconds:max_rate1m{job=\"${job}\"}",
     "legendFormat": "max"
    },
    {
     "expr": "job:process_cpu_seconds:median_rate1m{job=\"${job}\"}",
     "legendFormat": "median"
    },
    {
     "expr": "job:process_cpu_seconds:min_rate1m{job=\"${job}\"}",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "job:process_virtual_memory_bytes:max{job=\"${job}\"}",
     "legendFormat": "max"
    },
    {
     "expr": "job:process_virtual_memory_bytes:min{job=\"${job}\"}",
     "legendFormat": "min"
    },
    {
     "expr": "job:process_virtual_memory_bytes:median{job=\"${job}\"}",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "job:process_resident_memory_bytes:max{job=\"${job}\"}",
     "legendFormat": "max"
    },
    {
     "expr": "job:process_resident_memory_bytes:min{job=\"${job}\"}",
     "legendFormat": "min"
    },
    {
     "expr": "job:process_resident_memory_bytes:median{job=\"${job}\"}",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "Max FDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:process_max_fds:max{job=\"${job}\"}",
     "legendFormat": "max"
    },
    {
     "expr": "job:process_max_fds:max{job=\"${job}\"}",
     "legendFormat": "min"
    },
    {
     "expr": "job:process_max_fds:median{job=\"${job}\"}",
     "legendFormat": "median"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:process_open_fds:max{job=\"${job}\"}",
     "legendFormat": "max"
    },
    {
     "expr": "job:process_open_fds:min{job=\"${job}\"}",
     "legendFormat": "min"
    },
    {
     "expr": "job:process_open_fds:median{job=\"${job}\"}",
     "legendFormat": "median"
    }
   ]
  }
 ]
}