{
 "title": "Process Instance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": "up" },
   { "name": "instance", "query": "up" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:process_cpu_seconds:rate1m{instance=\"${instance}\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"${instance}\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"${instance}\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"${instance}\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "FDs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"${instance}\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{instance=\"${instance}\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}