# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Delta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Element_pb2 as Element__pb2
import DataFrame_pb2 as DataFrame__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Delta.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x44\x65lta.proto\x1a\rElement.proto\x1a\x0f\x44\x61taFrame.proto\"\\\n\x05\x44\x65lta\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1f\n\x0bnew_element\x18\x02 \x01(\x0b\x32\x08.ElementH\x00\x12\x1e\n\x08\x61\x64\x64_rows\x18\x03 \x01(\x0b\x32\n.DataFrameH\x00\x42\x06\n\x04type\"#\n\tDeltaList\x12\x16\n\x06\x64\x65ltas\x18\x01 \x03(\x0b\x32\x06.Deltab\x06proto3')
  ,
  dependencies=[Element__pb2.DESCRIPTOR,DataFrame__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DELTA = _descriptor.Descriptor(
  name='Delta',
  full_name='Delta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Delta.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_element', full_name='Delta.new_element', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='add_rows', full_name='Delta.add_rows', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='Delta.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=47,
  serialized_end=139,
)


_DELTALIST = _descriptor.Descriptor(
  name='DeltaList',
  full_name='DeltaList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deltas', full_name='DeltaList.deltas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=176,
)

_DELTA.fields_by_name['new_element'].message_type = Element__pb2._ELEMENT
_DELTA.fields_by_name['add_rows'].message_type = DataFrame__pb2._DATAFRAME
_DELTA.oneofs_by_name['type'].fields.append(
  _DELTA.fields_by_name['new_element'])
_DELTA.fields_by_name['new_element'].containing_oneof = _DELTA.oneofs_by_name['type']
_DELTA.oneofs_by_name['type'].fields.append(
  _DELTA.fields_by_name['add_rows'])
_DELTA.fields_by_name['add_rows'].containing_oneof = _DELTA.oneofs_by_name['type']
_DELTALIST.fields_by_name['deltas'].message_type = _DELTA
DESCRIPTOR.message_types_by_name['Delta'] = _DELTA
DESCRIPTOR.message_types_by_name['DeltaList'] = _DELTALIST

Delta = _reflection.GeneratedProtocolMessageType('Delta', (_message.Message,), dict(
  DESCRIPTOR = _DELTA,
  __module__ = 'Delta_pb2'
  # @@protoc_insertion_point(class_scope:Delta)
  ))
_sym_db.RegisterMessage(Delta)

DeltaList = _reflection.GeneratedProtocolMessageType('DeltaList', (_message.Message,), dict(
  DESCRIPTOR = _DELTALIST,
  __module__ = 'Delta_pb2'
  # @@protoc_insertion_point(class_scope:DeltaList)
  ))
_sym_db.RegisterMessage(DeltaList)


# @@protoc_insertion_point(module_scope)
