# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DataFrame_pb2 as DataFrame__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Map.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tMap.proto\x1a\x0f\x44\x61taFrame.proto\"!\n\x03Map\x12\x1a\n\x06points\x18\x01 \x01(\x0b\x32\n.DataFrameb\x06proto3')
  ,
  dependencies=[DataFrame__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='Map.points', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=63,
)

_MAP.fields_by_name['points'].message_type = DataFrame__pb2._DATAFRAME
DESCRIPTOR.message_types_by_name['Map'] = _MAP

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), dict(
  DESCRIPTOR = _MAP,
  __module__ = 'Map_pb2'
  # @@protoc_insertion_point(class_scope:Map)
  ))
_sym_db.RegisterMessage(Map)


# @@protoc_insertion_point(module_scope)
