# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StreamlitMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Delta_pb2 as Delta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='StreamlitMsg.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12StreamlitMsg.proto\x1a\x0b\x44\x65lta.proto\"N\n\x0cStreamlitMsg\x12\x14\n\nnew_report\x18\x01 \x01(\tH\x00\x12 \n\ndelta_list\x18\x02 \x01(\x0b\x32\n.DeltaListH\x00\x42\x06\n\x04typeb\x06proto3')
  ,
  dependencies=[Delta__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STREAMLITMSG = _descriptor.Descriptor(
  name='StreamlitMsg',
  full_name='StreamlitMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='new_report', full_name='StreamlitMsg.new_report', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delta_list', full_name='StreamlitMsg.delta_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type', full_name='StreamlitMsg.type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=35,
  serialized_end=113,
)

_STREAMLITMSG.fields_by_name['delta_list'].message_type = Delta__pb2._DELTALIST
_STREAMLITMSG.oneofs_by_name['type'].fields.append(
  _STREAMLITMSG.fields_by_name['new_report'])
_STREAMLITMSG.fields_by_name['new_report'].containing_oneof = _STREAMLITMSG.oneofs_by_name['type']
_STREAMLITMSG.oneofs_by_name['type'].fields.append(
  _STREAMLITMSG.fields_by_name['delta_list'])
_STREAMLITMSG.fields_by_name['delta_list'].containing_oneof = _STREAMLITMSG.oneofs_by_name['type']
DESCRIPTOR.message_types_by_name['StreamlitMsg'] = _STREAMLITMSG

StreamlitMsg = _reflection.GeneratedProtocolMessageType('StreamlitMsg', (_message.Message,), dict(
  DESCRIPTOR = _STREAMLITMSG,
  __module__ = 'StreamlitMsg_pb2'
  # @@protoc_insertion_point(class_scope:StreamlitMsg)
  ))
_sym_db.RegisterMessage(StreamlitMsg)


# @@protoc_insertion_point(module_scope)
