// automatically generated by the FlatBuffers compiler, do not modify
import * as NS7624605610262437867 from "./Schema"
/**
 * ----------------------------------------------------------------------
 * Arrow File metadata
 *
 *
 * @constructor
 */
export var org
;(function(org) {
  var apache
  ;(function(apache) {
    var arrow
    ;(function(arrow) {
      var flatbuf
      ;(function(flatbuf) {
        class Footer {
          constructor() {
            this.bb = null
            this.bb_pos = 0
          }
          /**
           * @param number i
           * @param flatbuffers.ByteBuffer bb
           * @returns Footer
           */
          __init(i, bb) {
            this.bb_pos = i
            this.bb = bb
            return this
          }
          /**
           * @param flatbuffers.ByteBuffer bb
           * @param Footer= obj
           * @returns Footer
           */
          static getRootAsFooter(bb, obj) {
            return (obj || new Footer()).__init(
              bb.readInt32(bb.position()) + bb.position(),
              bb
            )
          }
          /**
           * @returns org.apache.arrow.flatbuf.MetadataVersion
           */
          version() {
            let offset = this.bb.__offset(this.bb_pos, 4)
            return offset
              ? /**  */ this.bb.readInt16(this.bb_pos + offset)
              : NS7624605610262437867.org.apache.arrow.flatbuf.MetadataVersion
                  .V1
          }
          /**
           * @param org.apache.arrow.flatbuf.Schema= obj
           * @returns org.apache.arrow.flatbuf.Schema|null
           */
          schema(obj) {
            let offset = this.bb.__offset(this.bb_pos, 6)
            return offset
              ? (
                  obj ||
                  new NS7624605610262437867.org.apache.arrow.flatbuf.Schema()
                ).__init(this.bb.__indirect(this.bb_pos + offset), this.bb)
              : null
          }
          /**
           * @param number index
           * @param org.apache.arrow.flatbuf.Block= obj
           * @returns org.apache.arrow.flatbuf.Block
           */
          dictionaries(index, obj) {
            let offset = this.bb.__offset(this.bb_pos, 8)
            return offset
              ? (obj || new org.apache.arrow.flatbuf.Block()).__init(
                  this.bb.__vector(this.bb_pos + offset) + index * 24,
                  this.bb
                )
              : null
          }
          /**
           * @returns number
           */
          dictionariesLength() {
            let offset = this.bb.__offset(this.bb_pos, 8)
            return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0
          }
          /**
           * @param number index
           * @param org.apache.arrow.flatbuf.Block= obj
           * @returns org.apache.arrow.flatbuf.Block
           */
          recordBatches(index, obj) {
            let offset = this.bb.__offset(this.bb_pos, 10)
            return offset
              ? (obj || new org.apache.arrow.flatbuf.Block()).__init(
                  this.bb.__vector(this.bb_pos + offset) + index * 24,
                  this.bb
                )
              : null
          }
          /**
           * @returns number
           */
          recordBatchesLength() {
            let offset = this.bb.__offset(this.bb_pos, 10)
            return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0
          }
          /**
           * @param flatbuffers.Builder builder
           */
          static startFooter(builder) {
            builder.startObject(4)
          }
          /**
           * @param flatbuffers.Builder builder
           * @param org.apache.arrow.flatbuf.MetadataVersion version
           */
          static addVersion(builder, version) {
            builder.addFieldInt16(
              0,
              version,
              NS7624605610262437867.org.apache.arrow.flatbuf.MetadataVersion.V1
            )
          }
          /**
           * @param flatbuffers.Builder builder
           * @param flatbuffers.Offset schemaOffset
           */
          static addSchema(builder, schemaOffset) {
            builder.addFieldOffset(1, schemaOffset, 0)
          }
          /**
           * @param flatbuffers.Builder builder
           * @param flatbuffers.Offset dictionariesOffset
           */
          static addDictionaries(builder, dictionariesOffset) {
            builder.addFieldOffset(2, dictionariesOffset, 0)
          }
          /**
           * @param flatbuffers.Builder builder
           * @param number numElems
           */
          static startDictionariesVector(builder, numElems) {
            builder.startVector(24, numElems, 8)
          }
          /**
           * @param flatbuffers.Builder builder
           * @param flatbuffers.Offset recordBatchesOffset
           */
          static addRecordBatches(builder, recordBatchesOffset) {
            builder.addFieldOffset(3, recordBatchesOffset, 0)
          }
          /**
           * @param flatbuffers.Builder builder
           * @param number numElems
           */
          static startRecordBatchesVector(builder, numElems) {
            builder.startVector(24, numElems, 8)
          }
          /**
           * @param flatbuffers.Builder builder
           * @returns flatbuffers.Offset
           */
          static endFooter(builder) {
            let offset = builder.endObject()
            return offset
          }
          /**
           * @param flatbuffers.Builder builder
           * @param flatbuffers.Offset offset
           */
          static finishFooterBuffer(builder, offset) {
            builder.finish(offset)
          }
          static createFooter(
            builder,
            version,
            schemaOffset,
            dictionariesOffset,
            recordBatchesOffset
          ) {
            Footer.startFooter(builder)
            Footer.addVersion(builder, version)
            Footer.addSchema(builder, schemaOffset)
            Footer.addDictionaries(builder, dictionariesOffset)
            Footer.addRecordBatches(builder, recordBatchesOffset)
            return Footer.endFooter(builder)
          }
        }
        flatbuf.Footer = Footer
      })((flatbuf = arrow.flatbuf || (arrow.flatbuf = {})))
    })((arrow = apache.arrow || (apache.arrow = {})))
  })((apache = org.apache || (org.apache = {})))
})(org || (org = {}))
/**
 * @constructor
 */
;(function(org) {
  var apache
  ;(function(apache) {
    var arrow
    ;(function(arrow) {
      var flatbuf
      ;(function(flatbuf) {
        class Block {
          constructor() {
            this.bb = null
            this.bb_pos = 0
          }
          /**
           * @param number i
           * @param flatbuffers.ByteBuffer bb
           * @returns Block
           */
          __init(i, bb) {
            this.bb_pos = i
            this.bb = bb
            return this
          }
          /**
           * Index to the start of the RecordBlock (note this is past the Message header)
           *
           * @returns flatbuffers.Long
           */
          offset() {
            return this.bb.readInt64(this.bb_pos)
          }
          /**
           * Length of the metadata
           *
           * @returns number
           */
          metaDataLength() {
            return this.bb.readInt32(this.bb_pos + 8)
          }
          /**
           * Length of the data (this is aligned so there can be a gap between this and
           * the metatdata).
           *
           * @returns flatbuffers.Long
           */
          bodyLength() {
            return this.bb.readInt64(this.bb_pos + 16)
          }
          /**
           * @param flatbuffers.Builder builder
           * @param flatbuffers.Long offset
           * @param number metaDataLength
           * @param flatbuffers.Long bodyLength
           * @returns flatbuffers.Offset
           */
          static createBlock(builder, offset, metaDataLength, bodyLength) {
            builder.prep(8, 24)
            builder.writeInt64(bodyLength)
            builder.pad(4)
            builder.writeInt32(metaDataLength)
            builder.writeInt64(offset)
            return builder.offset()
          }
        }
        flatbuf.Block = Block
      })((flatbuf = arrow.flatbuf || (arrow.flatbuf = {})))
    })((arrow = apache.arrow || (apache.arrow = {})))
  })((apache = org.apache || (org.apache = {})))
})(org || (org = {}))

//# sourceMappingURL=File.mjs.map
