name: "Set GIT_TAG & GH_REPO env variables"

# Using an action to process user input (branch name) as an argument
# is the recommended approach for mitigating script injection attacks.
# It is not vulnerable to injection attacks, as the context value is not used
# to generate a shell script, but is instead passed to the action as an argument
# https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks

inputs:
  tag_name:
    description: 'Name of the tag'
  repo:
    description: 'The owner and repository name'

runs:
  using: composite
  steps:
    - name: Set GIT_TAG & GH_REPO
      env:
        GIT_TAG: ${{ inputs.tag_name }}
        GH_REPO: ${{ inputs.repo }}
      run: |
        echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
        echo "GH_REPO=$GH_REPO" >> $GITHUB_ENV
      shell: bash --login -eo pipefail {0}
