# TODO(lukasmasuch): This is only a temporary workflow to test the Starlette server in CI.
# It will be removed once the Tornado server is replaced by the Starlette server.
name: Playwright E2E Tests (Starlette)

on:
  push:
    branches:
      - "develop"
  pull_request:
    types: [opened, synchronize, reopened, labeled]

# Avoid duplicate workflows on same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-playwright-starlette
  cancel-in-progress: true

jobs:
  playwright-e2e-tests-starlette:
    # Run on push to develop, or on PRs with the 'starlette-tests' label
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'starlette-tests'))
    runs-on: ubuntu-latest-64-cores
    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2
      - name: Set Python version vars
        uses: ./.github/actions/build_info
      - name: Setup virtual env
        uses: ./.github/actions/make_init
        with:
          python_version: ${{ env.PYTHON_MAX_VERSION }}
      - name: Install playwright
        uses: ./.github/actions/playwright_install
      - name: Run make frontend-with-profiler
        run: make frontend-with-profiler
      - name: Get short SHA
        id: short_sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "sha_short=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT
          else
            echo "sha_short=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT
          fi
      - name: Run playwright tests with Starlette server
        run: |
          cd e2e_playwright
          rm -rf ./test-results
          pytest --use-starlette --ignore ./custom_components --browser webkit --browser chromium --browser firefox -n auto --reruns 1 -m "not performance"
      - name: Upload failed test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: playwright_starlette_test_results_${{ steps.short_sha.outputs.sha_short }}
          path: e2e_playwright/test-results
