---
name: Run Semgrep Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  run-semgrep-reusable-workflow:
    uses: snowflakedb/reusable-workflows/.github/workflows/semgrep-v2.yml@cc869f24324498871eaa135586ce360c3d271e25 # main
    secrets:
      token: ${{ secrets.SEMGREP_APP_TOKEN }}
