---
name: Run Semgrep Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  run-semgrep-reusable-workflow:
    uses: snowflakedb/reusable-workflows/.github/workflows/semgrep-v2.yml@863ab71d1133652ae3e7d1480ca7a4cb0b4f240c # main
    secrets:
      token: ${{ secrets.SEMGREP_APP_TOKEN }}
